"""Add research notes table

Revision ID: 2a87aee5974d
Revises: 1a6805a5758a
Create Date: 2026-09-19 10:39:46.359034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a87aee5974d'
down_revision: Union[str, Sequence[str], None] = '1a6805a5758a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_notes_id'), 'research_notes', ['id'], unique=False)
    op.create_index(op.f('ix_research_notes_paper_id'), 'research_notes', ['paper_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_notes_paper_id'), table_name='research_notes')
    op.drop_index(op.f('ix_research_notes_id'), table_name='research_notes')
    op.drop_table('research_notes')
    # ### end Alembic commands ###
